__tests__/Relude_String_test.re, src/Relude_String.re
Changed replace to replaceFirst and added replaceAll. Updated tests accordingly.
#31
=> Update replace with replaceFirst and add replaceAll

__tests__/Relude_Result_test.re, package-lock.json, package.json, src/Relude_IO.re, src/Relude_Result.re
- Close #32 - I think I was thinking about the args in terms of the
Result.t('a, 'e) type param order, but I 100% agree fold should have the error
handler first.
- Also removed redoc from package.json to get my local build running.
I'll properly remove redoc in another change.
=> Reverse arguments for Result.fold

__tests__/Relude_Array_test.re, docs/api/Relude_Array.html, src/Relude_Array.re
Adding documentation to `Relude_Array.re`
=> First pass at adding documentation.

__tests__/Relude_Float_test.re, __tests__/Relude_Int_test.re, src/Relude_Float.re, src/Relude_Int.re, src/Relude_String.re
Trying to make a consistent interface between the float/int/string modules for going into and out of a string.
=> Add from/to stringification for float/int/string

__tests__/Relude_Array_test.re, __tests__/Relude_Bool_test.re, __tests__/Relude_Float_test.re, __tests__/Relude_Function_test.re, __tests__/Relude_Identity_test.re, __tests__/Relude_Int_test.re, __tests__/Relude_ListF_test.re, __tests__/Relude_List_test.re, __tests__/Relude_NonEmpty_test.re, __tests__/Relude_Option_test.re, __tests__/Relude_String_test.re, __tests__/Relude_Validation_test.re, src/Relude_Float.re, src/Relude_Int.re, src/Relude_String.re
This was based on #58 and will be marked as ready after that is merged.
=> Run refmt on test files

src/Relude_IO.re
`IO.catchError` only handled the `Throw` variant so if you had an error in an `Async` variant you wouldn't catch it. Now it handles all of the cases that it should.
The only question I have is whether or not `Map` and `FlatMap` should be piped through this as well. I tried it but the compiler yelled at me so I stopped.
=> Have `IO.catchError` handle more cases

src/Relude_IO.re
`Map` and `FlatMap` weren't filled out before so those cases weren't handled correctly. Now they are :)
=> Finish all cases for catching an error

__tests__/Relude_AsyncData_test.re, __tests__/Relude_Result_test.re, package-lock.json, src/Relude_AsyncData.re, src/Relude_AsyncResult.re, src/Relude_Result.re
=> Additional functions for AsyncData/Result and Result

src/Relude.re, src/Relude_Globals.re
- Close #71
- Further changes to this can be made via additional PRs
=> Add Relude.Globals intended to be used for global opens

src/Relude_Option.re
Add documentation for `Relude_Option.re`
=> Document Relude_Option.

src/data/Relude_List.rei
Documentation for `Relude.List` with explanation of modules necessary for some functions
=> Document Relude_List

src/Relude_String.re
Documentation for `Relude_String.re`
Some of it is copied from https://bucklescript.github.io/bucklescript/api/Js.String.html and converted to ReasonML, but I wrote the portions that I copied, so I guess that’s self-plagiarism :) I hope this doesn’t cause any licensing problems.
=> String documentation

src/Relude_Map.re
I found myself needing to group things in an array/list quite often and thought that it would be helpful to be in Relude itself :)
This allows you to group any array/list into a Map with a grouping function.
=> Add grouping functions to Map functor

__tests__/Relude_IO_test.re, src/Relude_IO.re
I cluttered up this PR with some cleanup, but here are the relevant changes:
`flip`
https://github.com/reazen/relude/pull/182/files#diff-20e950ef5684753148b8995bdb93bd0fR481
`summonError`
https://github.com/reazen/relude/pull/182/files#diff-20e950ef5684753148b8995bdb93bd0fR544
`unsummonError`
https://github.com/reazen/relude/pull/182/files#diff-20e950ef5684753148b8995bdb93bd0fR617
Now I'll attempt to describe the problem, my likely-flawed logic about what's going on, and the proposed solution.
In the `FlatMap(Async)` case of IO in these functions (`flip`/`summonError`/`unsummonError`), we were previously resolving the given `IO` from the `FlatMap`, then using `io |> tap/bitap` as a mechanism to call the `onDone` callback of the `Async`, but this just doesn't seem to get the job done.  I …
=> Possible fix for various non-terminating IO functions

__tests__/Relude_IO_test.re, src/Relude_IO.re
Some exploratory code for issue https://github.com/reazen/relude/issues/171
=> Add `Cancel` to IO

__tests__/Relude_IO_test.re, src/extensions/Relude_Extensions_Applicative.re
The recent blog post inspired me to add this to the extensions. Figured it'd be helpful to people. LMK if there is anything else you would like me to add.
=> Add `all` to Applicative extensions

__tests__/Relude_String_test.re, src/Relude_String.re
Resolve #209 
This is just an initial cut that seems to work, but we can change it later if needed.
=> Add String.padStart and padEnd

__tests__/Relude_AsyncResult_test.re
=> Increase coverage of AsyncResult module

__tests__/js/Relude_Js_Promise_test.re
=> Increase coverage of Js.Promise module 

__tests__/Relude_Function_test.re
=> Increase coverage of Function module

__tests__/Relude_Validation_test.re, src/Relude_Validation.re
=> Increase coverage of Validation module

__tests__/js/Relude_Js_Exn_test.re, __tests__/js/Relude_Js_Json_test.re
Now `Relude_Js_Exn`, `Relude_Js_Json` and `Relude_Js_Promise` are  100%.
(`Relude_Js_Animation` and  `Relude_Js_Console` hasn't covered yet)
=> Increase coverage of Js modules

__tests__/Relude_IO_test.re
=> Increase coverage of IO module

__tests__/Relude_Ior_test.re
=> Increase code coverage of Ior module

src/Relude_Set.re
Adds `toggle` function for Set that adds a value if it is not part of the set already or removes it if it is.
=> add Set.toggle

src/array/Relude_Array_Base.re, src/list/Relude_List_Base.re, src/option/Relude_Option_Base.re
=> Add keep/reject for List/Array/Option

src/Relude.re
Fix a broken link in https://reazen.github.io/relude/api/index.html
=> Fix documentation link

__tests__/extensions/Relude_Extensions_Enum_test.re, src/extensions/Relude_Extensions_BoundedEnum.re
=> Inverse map functions follow-on

.github/workflows/ci.yml, .gitignore, README.md, docs/Conventions.md, docs/Developers.md, docs/FAQ.md, docs/Overview.md, docs/README.md, docs/_coverpage.md, dune, package.json, src/Relude.re, src/Relude_Float.re, src/Relude_Globals.re, src/Relude_IO.re, src/js/Relude_Js.re, yarn.lock
I accidentally merged the "bump Melange version" work straight to `master`, but this PR will have some follow up work to:
- fix CI
- make documentation more clear for use with Melange instead of Bucklescript
=> Build with melange in CI
