reazen/relude

- __tests__/Relude_AsyncData_test.re
- __tests__/Relude_AsyncResult_test.re
- src/Relude_AsyncData.re
- src/Relude_AsyncResult.re
This fixes #33 and adds several additional helpers. I added tests to confirm my current expectations, but if people disagree with those expectations, or if we find the names confusing, I'm certainly open to changes.
I also ran `refmt` on the files, which added some noise to the diff.
> Add helpers to AsyncData and AsyncResult

- __tests__/Relude_Array_test.re
- __tests__/Relude_List_test.re
- __tests__/Relude_Option_test.re
- src/Relude_Array.re
- src/Relude_Identity.re
- src/Relude_List.re
- src/Relude_NonEmpty.re
- src/Relude_Option.re
- src/Relude_Sequence.re
- src/Relude_Void.re
- Closes #28 - changes all functions that were previously named showF,
eqF, etc. to showBy, eqBy, etc.  I tried to find them all, but it's
possible that I missed some, which we can fix as we find them.
> Rename *F functions to *By

- __tests__/Relude_List_test.re
- src/Relude_Array.re
- src/Relude_List.re
Fix `take()`, `takeUpTo()`, `drop()`, `dropUpTo()`, and `splitAt()` to return `None` or the empty array (depending upon their return type) when given a negative index.
> Fix negative indices.

- __tests__/Relude_Option_test.re
- __tests__/Relude_Result_test.re
- src/Relude_Option.re
- This was a result of our shuffling of flatMap/bind functions.
- Closes #47
> Fix Option Infix (>>=) argument order

- .circleci/config.yml
- src/Relude.re
- src/Relude_IO.re
- src/Relude_JsExn.re
- src/Relude_JsPromise.re
- src/Relude_Unsafe.re
The Js.Promise error handling is strange, sometimes it uses the OCaml
extensible `exn` type and sometimes `Js.Promise.error` (an opaque type).
Neither of these seem quite right, but we have to satisfy the compiler
somehow.
> Ideas on Promise/IO conversions

- __tests__/Relude_Option_test.re
- __tests__/testUtils/FS.re
- src/Relude_IO.re
- src/Relude_List.re
- src/Relude_Option.re
- Closes #44
- We have decided that Option `fold` and `getOrElse` functions should take a strict
default value for the `None` case, and the `foldLazy`/`getOrElseLazy`
functions should be the lazy alternatives.  The rationale is that it's
more convenient to just construct and throw away the default value 99%
of the time.  The `Lazy` version of the function is available in cases
where the default value is expensive to construct.
> Change Option fold/foldStrict to foldLazy/fold (and same for getOrElse)

- __tests__/Relude_Array_test.re
- __tests__/Relude_List_test.re
- __tests__/Relude_String_test.re
- src/Relude_Array.re
- src/Relude_List.re
- src/Relude_String.re
- Closes #46
- Renamed all bare `get` and `set` functions to avoid the dreaded
`String.get` shadowing and the refmt treatment of such functions.
> Remove get and set functions to avoid refmt/shadowing issues

- src/data/Relude_Array.rei
Document the submodules for `Relude.Array` (still missing documentation for `<=<` and `>=>`)
> Array submodules

- __tests__/Relude_Array_test.re
- __tests__/Relude_AsyncData_test.re
- __tests__/Relude_AsyncResult_test.re
- __tests__/Relude_Result_test.re
- src/Relude_AsyncData.re
- src/Relude_AsyncResult.re
- src/Relude_Result.re
- src/Relude_String.re
- `Relude.Result.eqBy: (errEq, okEq, resultA, resultB) => bool`
- `Relude.AsyncResult.eqBy: (errEq, okEq, asyncA, asyncB) => bool`
- `Relude.AsyncData.eqBy: (innerEq, asyncA, asyncB) => bool`
I'm realizing the above isn't valid syntax, but it's less verbose than writing out the full signature, and it explains what's going on.
Also, there seems to be some issue with the inferred type of `Relude.String.Eq` which makes it impossible to get into the inner functions, but at least now you can use `Relude.String.eq` like a champ.
> Equality checks for Result and Async*

- src/data/Relude_Array.rei
- src/data/Relude_List.rei
Rewrote documentation for `Relude_Array` to take account of use of `ORD`, `EQ`, `MONOID`, and `SHOW` modules for some of the functions. This required discussing each of them in a long comment at the beginning of the module. 
`module Validation` is as yet undocumented, as I am not sure what it does / how it works / what part of it *needs* to be documented.
> Array with modules

- src/data/Relude_Array.rei
* Changed some occurrences of `list` to `array`.
* Fixed module comment for `module Float`.
* Changed example of module for `removeEach` to reference `EQ` module type.
> Minor typos; shorten doc for removeEach.

- __tests__/Relude_Array_test.re
- __tests__/Relude_List_test.re
- src/data/list/Relude_List_Base.re
Fix problem noted in https://github.com/reazen/relude/issues/85 so that `Array.replicate()` and `List.replicate()` return the empty array/list when the count is zero or negative.
> Make List.replicate() return [] for non-positive n.

- src/Relude_Result.re
Would like feedback on documentation for `map2()`..`map5()`; I think the examples work better than just passing `Ok()` and `Error()` values that don’t come from any context.
> Add documentation for Relude_Result.

- src/Relude_Function.re
The documentation for `bind()` and `apply()` tells what they do, but doesn’t tell *why* or *how*. If anyone wants to add verbiage about that, I would appreciate it.
> Document Relude.Function.

- .gitattributes
- .gitignore
- __tests__/Relude_Array_test.re
- __tests__/Relude_List_test.re
- src/array/Relude_Array_Base.re
- src/list/Relude_List_Base.re
Bucklescript's OCaml version doesn't yet support `[@tailcall]` so for now I just made a huge list in a test to ensure tail recursion. The test was failing prior to the change to `prependToAll`.
> Tail recursive intersperse

- src/Relude_Map.re
Currently, the `Map.groupBy` wants a `Map.Comparable.t` instead of the `Map.key`. These types should be the same but that isn't explicit in the module definition and it's opaque to consumers so the type signature of this needs to switch to be explicitly the key of the map.
> Fix incorrect type signature for `Map.groupBy`

- src/Relude_AsyncResult.re
I'm assuming this `Relude_AsyncResult.toIdle` should correspond to `Relude_AsyncData.toIdle`, in the same way as `Relude_AsyncResult.toBusy` corresponds to `Relude_AsyncData.toBusy`?
> Fix AsyncResult.toIdle

- src/js/Relude_Js_Exn.re
drawn from https://github.com/BuckleScript/bucklescript/issues/3839
Note this form of raw convinces the compiler that it is a function, i.e, pure value declaration
> replace 100% dangerous raw with less danger raw

- __tests__/Relude_IO_test.re
- src/Relude_IO.re
When an `IO` with an `Async` constructor is sent through a `flatMap`
which we then `summonError` on, the `onDone` of `Async` constructor is
never called which means that the IO will never resolve.
It seems that switching the `tap` to a `bitap` fixes this issue.
> Fix `IO.summonError`

- __tests__/Relude_Float_test.re
- src/extensions/Relude_Extensions_Ord.re
When using comparison operators for ORD typeclasses, it's somewhat
ambiguous which one is being compared to which.
For example if you want to see 2 is less than 3 then you have to know
that with using the `OrdExtensions` methods that 2 has to come before
3 in the arg order. Also, when partially applying or when using `|>`
things don't read very well (e.g. `3.0 |> Float.lessThan(2.0)`).
By using a named parameter, the thought is that this can help clear that
up by making it explicit what is being compared to (e.g.
`2.0 |> Float.Named.lessThan(~compareTo=3.0)`)
The new functions are in a submodule called `Named` which was the done
to keep backwards compatibility. I'm not 100% on the naming of things
but I wanted to open this and start a conversation about what would be a
way forward that …
> Add `Named` comparison operators for ORD typeclass

- src/Relude_IO.re
The code comment/documentation seems to be a leftover copy/paste from `fromOption`
> Fix IO `fromResult` code documentation

- __tests__/Relude_IO_test.re
- __tests__/Relude_ResultT_test.re
- src/Relude_IO.re
- src/Relude_ResultT.re
More useful methods lifted from cats, based on: https://github.com/typelevel/cats/blob/c56edd78e6accfc276bfffad15d08d309a76076e/core/src/main/scala/cats/data/EitherT.scala#L739-L754
If you're happy to add these, then I'll cover them with tests and rebase tomorrow.
> Cond methods for IO and ResultT

- __tests__/Relude_RIO_test.re
- src/Relude_RIO.re
> Initial RIO Monad

- src/Relude_Set.re
When working with sets, sometimes you need to update a value in the set 
and not just add a value to it only when it doesn't exist previously.
This function will remove an entry from the set if it's there and will 
add the new version of it into the set afterwards.
> Add Set.update

- src/Relude_IO.re
- src/Relude_RIO.re
- src/Relude_ReaderT.re
- src/Relude_Result.re
- src/Relude_ResultT.re
- src/Relude_SequenceZipper.re
- src/Relude_Set.re
- src/Relude_StateT.re
- src/js/Relude_Js.re
- src/js/Relude_Js_Json.re
- src/option/Relude_Option_Instances.re
- Closes #205 (hopefully)
- The re-aliased `(>>)`/`(<<)` operators were causing shadowing warnings
in certain contexts - see #205 for example
- I went ahead and removed a few places where we had module aliases too.
It's unfortunate that we can't "import" (alias) our own modules and not cause
shadowing issues.
> Remove operator and module aliases

- __tests__/Relude_TreeZipper_test.re
- __tests__/Relude_Tree_test.re
- src/Relude.re
- src/Relude_Globals.re
- src/Relude_Tree.re
- src/Relude_TreeZipper.re
- src/Relude_Tuple.re
- Adds a `TreeZipper` - similar to `ListZipper`, but for a multi-way "rose" tree, like `Relude_Tree`
- Allows you to "navigate" within a Tree and manipulate the values around you
- See Tony Morris' presentation here for more info: http://data.tmorris.net/talks/zippers/bd054c210649101b84662c614fc45af3c27a5eef/zippers.pdf
- I have not implemented all the typeclasses (Apply/Applicative/Monad/Comonad/Foldbale/etc.) at this time, but that can be done in the future.
> TreeZipper type and tests

- __tests__/Relude_Array_test.re
- __tests__/Relude_List_test.re
- src/array/Relude_Array_Base.re
- src/list/Relude_List_Base.re
There's `replaceAt` but no `insertAt` at the moment for both Array and List.
Would you be ok if I open another pull request with `updateAt : int -> ('a -> 'a) -> list('a) -> list('a)`?
> Add Array.insertAt and List.insertAt

- __tests__/Relude_Float_test.re
- __tests__/Relude_String_test.re
- src/Relude_Float.re
- src/Relude_String.re
- Add `String.charCodeAt` (with safe `option(int)` return instead of Bucklescript's NaN-able float)
- Add `String.charAtOrEmpty` (convenience for falling back to empty string)
- Add `Float.isNaN`
- Add `pow` and `sqrt` to Float (mostly for testing `nan`, but also because they're useful?)
> Helpers for dealing with charCodes and NaN floats

- __tests__/Relude_NonEmpty_test.re
* Before: `58.81%` Statements
* After: `61.29%` Statements
Sorry, I'm unable to make coverage higher, I don't know how to deal with `module` function, for example: `function WithSequence(TailSequence) {}`:
> Improve NonEmpty coverage

- __tests__/Relude_IO_test.re
- __tests__/Relude_Ior_test.re
- __tests__/Relude_Option_test.re
- __tests__/Relude_Result_test.re
- __tests__/Relude_Validation_test.re
- src/Relude_IO.re
- src/Relude_Interface.re
- src/Relude_Ior.re
- src/Relude_Result.re
- src/Relude_Validation.re
- src/extensions/Relude_Extensions_Align.re
- src/extensions/Relude_Extensions_Semialign.re
- src/ior/Relude_Ior_Type.re
- src/option/Relude_Option_Instances.re
Closes #188 
Before this PR, `Ior` had constructors `IOk('a)`, `IError('e)`, and `IBoth('a, 'e)`, but this makes the type more semantic, and less useful for the purposes below. I changed the constructors to `This('a)`, `That('b)`, and `Both('a, 'b)`. This still allows for success/fail semantics (`This` being success, and `That` being failure), but it also allows the type to be used for less-semantic things, like `ALIGN`.
This was a breaking change in `Ior`, but should be easy to fix - just rename `IOk` to `This`, `IError` to `That`, and `IBoth` to `Both` (and other similar name changes).
- `catThis`, `catThat`, `merge`, `fold`, etc. - see files changed
```reason
module type SEMIALIGN = {
include BsAbstract.Interface.FUNCTOR;
let align: (t('a), t('b)) => t(Relude_Ior_Type.t('a, 'b));
let …
```
> Ior and ALIGN

- __tests__/Relude_Array_test.re
- package-lock.json
- package.json
- src/Relude_Interface.re
- src/Relude_NonEmpty.re
- src/Relude_Sequence.re
- src/Relude_SequenceZipper.re
- src/Relude_Tree.re
- src/array/Relude_Array_Instances.re
There's more that can be done for `bs-platform@7` (e.g. we could start preferring `result` over `Belt.Result` and take advantage of the always-in-scope result constructors; maybe there's some unboxing to be done), but for now the most important thing is to make sure it builds.
In order to do that, I'm depending on a `bs-abstract` pull request. Hopefully that gets merged soon, but a friendly fork would be an option if we want to get a release out quickly. Additionally, I've had to remove some of the array typeclass implementations (Monoid Any, Plus, Alternative, Monad Plus). I was able to keep `NonEmptyArray` around (I think without any breaking changes to NEA, but I did have to change the module type of `Sequence` slightly).
I'll try to put together a list of what changed, and we probably …
> Make it build with latest Bucklescript

- __tests__/Relude_TreeZipper_test.re
- src/Relude_TreeZipper.re
> Reverse order of leftSiblings when moving up a TreeZipper

- __tests__/Relude_TreeZipper_test.re
- src/Relude_TreeZipper.re
I'm not exactly sure what the problem was but looking at the old version, I would guess that a zipper would never `moveRight` more than a single time per depth.
I devised new test cases for `findInFocusAndChildren` that would all fail on the old version.
---
Also added a new utility function called `findInFocus`. Please tell me if you find it useful. :grinning:
> Fix TreeZipper.findInFocusAndChildren logic

- __tests__/js/Relude_Js_Promise_test.re
- src/js/Relude_Js_Promise.re
All of the functions available for converting an IO forced the error into the opaque error channel  which is a little hard to deal with. It would be nice if there was an option to keep the result in the success channel and deal with the error later in a more predictable way.
> Add `fromIOWithResult` for getting a promise from an IO

- __tests__/Relude_List_test.re
- src/list/Relude_List_Instances.re
I had meant to add the unfold interface and various implementations to Relude after getting them merged to `bs-bastet`, but forgot since I was using bastet's unfold directly.
I see you're already using the bastet interface for your Tree `unfold`, which is cool.
Here I've just hooked up bastet's list unfold and added a test.
> Add list unfold

- src/Relude_Map.re
- src/Relude_Set.re
This makes the API a little more consistent since #245 landed
> Add keep/reject for Set/Map

- package-lock.json
- package.json
This will fix an error like this"
```sh
npm test
> relude@0.63.0 test /Repos/relude
> jest
● Validation Error:
Module bisect_ppx/lib/js/src/runtime/bucklescript/jest.js in the setupFilesAfterEnv option was not found.
<rootDir> is: /Repos/relude
Configuration Documentation:
https://jestjs.io/docs/configuration.html
npm ERR! Test failed.  See above for more details.
```
> Upgrade bisect ppx to 2.4.1 and fix setupFilesAfterEnv config

- __tests__/Relude_Result_test.re
- src/Relude_Result.re
As discussed in: https://github.com/reazen/relude/issues/285
This PR adds the following three functions:
```reason
getOrElseBy: ('e => 'a, result('a, 'e)) => 'a
getErrorOrElse: ('e, result('a, 'e)) => 'e)
getErrorOrElseBy: ('a => 'e, result('a, 'e)) => 'e
```
Since these are a bit niche, the examples are a bit niche as well. Given the rest of the examples they might be a bit verbose. Please let me know if that's the case, then I'll try and make it less so.
The PR can be reviewed commit-by-commit.
> Add Result Extraction Helpers

- __tests__/extensions/Relude_Extensions_Enum_test.re
- src/extensions/Relude_Extensions_BoundedEnum.re
This PR adds two functions based on [inverseMap](https://hackage.haskell.org/package/relude-0.6.0.0/docs/Relude-Extra-Enum.html#v:inverseMap) from Haskell's `relude` library.
The idea is, given an ordered bounded enum `t` and a function that maps each `t` value to a unique `a` value, we can derive the inverse mapping function from that particular set of `a` values to their corresponding `t` values. Obviously, we can't account for *all* `a` values, so `inverseMap` must return `option(t)`.
This is particularly nice if you already have a `show` function, and want to generate the inverse function to parse strings to that data type.
Note:
Functions generated using `inverseMap` will never be as efficient as their hand-written counterparts. This is because they need to perform dynamic lookups to …
> Inverse map functions

- .vscode/settings.json
- __tests__/Relude_Set_test.re
- esy.json
- esy.lock/index.json
- esy.lock/opam/dot-merlin-reader.4.2/opam
- src/Relude_Set.re
- Fix ocamllsp in vscode, following the instructions here: https://github.com/trite/trite.io-content/blob/main/posts/2022/2022-06-10_melange-ocamllsp-vscode.md
- Add a `singleton` constructor to `Set`. This isn't named `pure` in part to be consistent with `Map`, and in part because `Set` is not a valid `Applicative` because the `map` operation is not guaranteed to preserve the structure
- Add a handful of tests to what was previously an untested module
> Add `singleton` to Set

- __tests__/Relude_AsyncResult_test.re
- src/Relude_AsyncResult.re
This adds an `alt` function and an `Alt` typeclass instance to `Relude.AsyncResult`. The rules are as follows (with some tests provided that hopefully ensure this):
- When both AsyncResults are in the same error state (both Complete or both Reloading), the first is returned
- `Complete(Error(_))` is preferred over `Reloading(Error(_))`
- All non-error states are preferred over an error
- When neither is an error, the rules from AsyncData's `alt` apply (Complete > Reloading > Loading > Init)
> Add `alt` for AsyncResult

- docs/README.md
- docs/_coverpage.md
- package.json
And by "fix" I mean "remove."
I forget why I added it in the first place, but I think I was just trying to more clearly express the expected node version for CI and local dev. I hadn't realized that setting the `engines` field in `package.json` can actually prevent your package from being installed in cases where the local Node version doesn't match. That's really dumb and not at all what I wanted.
> Fix node engine version
